In [2]:
import pandas as pd
import numpy as np

In [3]:
train=pd.read_csv('data/train.csv')
test=pd.read_csv('data/test.csv')

In [4]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b


In [6]:
print(a)
print(b)
c

[[-0.37755354 -0.11598237 -1.14379745]
 [-1.27732763  0.11906881 -1.65138266]
 [-0.44649602 -2.42515899  0.93782291]]
[[ 0.68776995]
 [ 0.18697334]
 [-0.66805397]]


array([[-0.25966998, -0.07976919, -0.78666952],
       [-0.23882621,  0.02226269, -0.30876453],
       [ 0.29828344,  1.62013708, -0.62651632]])